{
  "contest": 90,
  "handle": "0xDjango",
  "address": "0x5938Dc681121c306192F3187a3EEe47B9C697BA0",
  "risk": "2",
  "title": "Potentially Incomplete or Stale Data from Oracle",
  "issueId": 46,
  "issueUrl": "https://github.com/code-423n4/2022-04-phuture-findings/issues/46"
}